// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "SearchEngineService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace examples::searchengine;

class SearchEngineServiceHandler : virtual public SearchEngineServiceIf {
 public:
  SearchEngineServiceHandler() {
    // Your initialization goes here
  }

  void search(SearchResponse& _return, const SearchRequest& request) {
    // Your implementation goes here
    printf("search\n");
  }

  int32_t ping() {
    // Your implementation goes here
    printf("ping\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<SearchEngineServiceHandler> handler(new SearchEngineServiceHandler());
  shared_ptr<TProcessor> processor(new SearchEngineServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

