/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "service_api_constants.h"

namespace examples { namespace searchengine {

const service_apiConstants g_service_api_constants;

service_apiConstants::service_apiConstants() {
}

}} // namespace

