/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef service_api_CONSTANTS_H
#define service_api_CONSTANTS_H

#include "service_api_types.h"

namespace examples { namespace searchengine {

class service_apiConstants {
 public:
  service_apiConstants();

};

extern const service_apiConstants g_service_api_constants;

}} // namespace

#endif
